{
	"id": "CVE-2025-29630",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Awaiting Analysis",
	"published": "2025-07-25T17:15:31.347",
	"lastModified": "2025-07-29T14:14:55.157",
	"descriptions": [
		{
			"lang": "en",
			"value": "An issue in Gardyn 4 allows a remote attacker with the corresponding ssh private key can gain remote root access to affected devices"
		},
		{
			"lang": "es",
			"value": "Un problema en Gardyn 4 permite que un atacante remoto con la clave privada ssh correspondiente pueda obtener acceso root remoto a los dispositivos afectados."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "http://gardyn.com"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://github.com/mselbrede/gardyn/blob/main/CVE-2025-29630.md"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "LOW",
					"userInteraction": "NONE",
					"scope": "UNCHANGED",
					"confidentialityImpact": "HIGH",
					"integrityImpact": "HIGH",
					"availabilityImpact": "NONE",
					"baseScore": 8.1,
					"baseSeverity": "HIGH"
				},
				"exploitabilityScore": 2.8,
				"impactScore": 5.2
			}
		]
	},
	"weaknesses": [
		{
			"source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
			"type": "Secondary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-284"
				}
			]
		}
	]
}
