{
	"id": "CVE-2024-4878",
	"sourceIdentifier": "security@openvpn.net",
	"vulnStatus": "Rejected",
	"published": "2025-05-19T14:15:22.023",
	"lastModified": "2025-05-19T14:15:22.023",
	"descriptions": [
		{
			"lang": "en",
			"value": "Rejected reason: Unused CVE record, incorrectly reserved"
		}
	],
	"references": [],
	"metrics": {}
}
